### ISSUE TITLE
Plugin not installed

### ISSUE THREAD

**Issue by tammaroivan** [tammaroivan/compras#4]
Hello! Im trying to use @ionic-native/diagnostic , specifically diagnostic.isLocationEnabled, when I try it from my android smartphone the promise returns me “plugin_not_installed”

In `cordova plugin list` i get:

`cordova.plugins.diagnostic 3.7.2 "Diagnostic"`

In config.xml I have

`<plugin name = "cordova.plugins.diagnostic" spec = "^ 3.7.2" />`

I tried to put it also inside

`platform.ready (). then (...`

But I keep getting the same error

In the constructor im doing
```
this.plt.ready().then( ()=> {
this.diagnostic.isLocationEnabled()
.then((state) => {
if(state){
this.locationState=true;
} else {
this.locationState=false;
}
}).catch(e => {this.presentAlert(JSON.stringify(e));this.locationState=false;});
});

```
presentAlert is for show the error in a alert

**Comment by ivodan** [comment]
Este error es solo de ionic view. Testeando por usb funciona correctamente.
